export const PUBLIC_UPLOAD_MAX_MB = 25;
export const SIGNED_UPLOAD_MAX_MB = 10;

export const PUBLIC_UPLOAD_MAX_BYTES = PUBLIC_UPLOAD_MAX_MB * 1024 * 1024;
export const SIGNED_UPLOAD_MAX_BYTES = SIGNED_UPLOAD_MAX_MB * 1024 * 1024;
